export const theme = {
  colors: {
    white: '#ffffff',
    black: '#000000',
    grey: '#4d4d4d',
    background: '#f7a7bb',
    pink: '#facad6',
    border: '#d9d9d9',
    danger: '#dc2626',
  },
  typography: {
    xs: '1.2rem',
    sm: '1.4rem',
    base: '1.6rem',
    lg: '1.8rem',
    xl: '2rem',
    xxl: '2.4rem',
    xxxl: '3rem',
    display: '3.6rem',
  },
  weights: {
    regular: 400,
    medium: 500,
    semibold: 600,
    bold: 700,
  },
  spacing: {
    xxs: '0.4rem',
    xs: '0.8rem',
    sm: '1.2rem',
    md: '1.6rem',
    lg: '2.4rem',
    xl: '3.2rem',
    xxl: '4rem',
    xxxl: '4.8rem',
  },
  radius: {
    xs: '0.4rem',
    sm: '0.8rem',
    md: '1.2rem',
    lg: '1.6rem',
    xl: '2.4rem',
    round: '9999px',
  },
};
