export const colorValues = {
  white: '#ffffff',
  black: '#000000',
  grey: '#4d4d4d',
  background: '#f7a7bb',
  pink: '#facad6',
  surface: '#ffffff',
  surfaceSoft: '#facad6',
  surfaceMuted: '#f7a7bb',
  shadowLight: 'rgba(0, 0, 0, 0.1)',
  shadowMedium: 'rgba(0, 0, 0, 0.2)',
  shadowDark: 'rgba(0, 0, 0, 0.3)',
}

export const theme = {
  color: {
    white: 'var(--white-color)',
    black: 'var(--black-color)',
    grey: 'var(--grey-color)',
    background: 'var(--background-color)',
    pink: 'var(--pink-color)',
    surface: 'var(--surface-color)',
    surfaceSoft: 'var(--surface-soft-color)',
    surfaceMuted: 'var(--surface-muted-color)',
    transparent: 'transparent',
  },
  shadow: {
    light: 'var(--shadow-light)',
    medium: 'var(--shadow-medium)',
    dark: 'var(--shadow-dark)',
    panel: '0 18px 45px var(--shadow-light)',
    modal: '0 24px 80px var(--shadow-dark)',
    hole: 'inset 0 10px 18px var(--shadow-dark)',
    pressed: 'inset 0 -8px 0 var(--shadow-medium)',
    lifted: '0 12px 28px var(--shadow-medium)',
    tableRow: '0 8px 18px var(--shadow-light)',
  },
  spacing: {
    none: '0',
    xxs: '4px',
    micro: '6px',
    xs: '8px',
    sm: '10px',
    md: '12px',
    lg: '13px',
    xl: '14px',
    xxl: '15px',
    xxxl: '16px',
    section: '18px',
    overlay: '20px',
    page: '32px',
    panel: '22px',
    board: '24px',
    modal: '28px',
  },
  radius: {
    sm: '8px',
    round: '999px',
    circle: '50%',
  },
  fontSize: {
    xs: '13px',
    sm: '14px',
    panelTitle: '22px',
    statusValue: '23px',
    modalTitle: '28px',
    title: '32px',
    target: 'clamp(18px, 4vw, 34px)',
  },
  fontWeight: {
    bold: 700,
    extraBold: 800,
    black: 900,
  },
  opacity: {
    disabledButton: 0.48,
    disabledLevel: 0.7,
  },
  size: {
    minViewport: '320px',
    contentMax: '1080px',
    controlMin: '280px',
    controlMax: '360px',
    boardMin: '320px',
    boardMax: '540px',
    boardGapMax: '18px',
    rankingEmptyHeight: '220px',
    boardAreaHeight: '560px',
    messageHeight: '48px',
    statusHeight: '76px',
    tabMinWidth: '84px',
    dangerButtonMinWidth: '98px',
    modalMaxWidth: '420px',
  },
  breakpoint: {
    main: '820px',
    board: '620px',
    table: '680px',
  },
  viewport: {
    boardGapFluid: '2.4vw',
  },
  line: {
    thin: '1px',
    targetOffset: '18%',
  },
  background: {
    page: 'var(--pink-color)',
    boardArea: 'var(--white-color)',
    hole: 'var(--black-color)',
  },
}
